# Generated by Django 6.0 on 2025-12-30 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0013_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MySenzApp.subcategory'),
            preserve_default=False,
        ),
    ]
