# Generated by Django 6.0 on 2025-12-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0014_service_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='subCategory',
            new_name='subcategory',
        ),
    ]
