# Generated by Django 6.0 on 2026-01-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0015_rename_subcategory_service_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='FFSI_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/drug_license/'),
        ),
        migrations.AddField(
            model_name='store',
            name='dl_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/drug_license/'),
        ),
        migrations.AddField(
            model_name='store',
            name='gst',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='gst_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='store/gst_certificates/'),
        ),
    ]
