# Generated by Django 6.0 on 2026-01-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0016_store_ffsi_image_store_dl_image_store_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='dl',
            field=models.CharField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='gst',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
