# Generated by Django 6.0 on 2025-12-29 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowBill', '0015_indentstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'uom',
            },
        ),
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(max_length=50, unique=True)),
                ('grn_type', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('Partial', 'Partial'), ('Full', 'Full')], max_length=20)),
                ('dispatch_id', models.IntegerField(blank=True, null=True)),
                ('request_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='FlowBill.purchaseorder')),
            ],
            options={
                'db_table': 'grn',
            },
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('accepted_qty', models.IntegerField()),
                ('rejected_qty', models.IntegerField(default=0)),
                ('uom', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=50)),
                ('creted_at', models.DateTimeField(auto_now_add=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='FlowBill.grn')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FlowBill.medicine')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FlowBill.product')),
            ],
            options={
                'db_table': 'grn_item',
            },
        ),
        migrations.AddIndex(
            model_name='grn',
            index=models.Index(fields=['purchase_order'], name='grn_purchas_f57cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='grn',
            index=models.Index(fields=['status'], name='grn_status_5ca68c_idx'),
        ),
        migrations.AddIndex(
            model_name='grnitem',
            index=models.Index(fields=['product', 'batch_no'], name='grn_item_product_d08cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='grnitem',
            index=models.Index(fields=['medicine', 'batch_no'], name='grn_item_medicin_642983_idx'),
        ),
    ]
