# Generated by Django 6.0 on 2025-12-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowBill', '0016_uom_grn_grnitem_grn_grn_purchas_f57cb4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
