# Generated by Django 6.0 on 2026-01-02 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowBill', '0018_rename_categories_vendor_sub_categories_and_more'),
        ('MySenzApp', '0017_store_dl_alter_store_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='indentitem',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='medicine',
        ),
        migrations.RemoveIndex(
            model_name='grnitem',
            name='grn_item_medicin_642983_idx',
        ),
        migrations.AddField(
            model_name='grnitem',
            name='damaged_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grnitem',
            name='expired_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grnitem',
            name='finala_ptr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grnitem',
            name='mrp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grnitem',
            name='received_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indent',
            name='remarkers',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='MySenzApp.subcategory'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='grnitem',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
